import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';

/**
 * Tailwind v3 config wired to shadcn's HSL CSS-variable tokens (defined in
 * src/tokens.css and regenerated by the founding.dev tokenSeedService).
 *
 * When tokens.css is rewritten on turn 1, every utility here that reads
 * hsl(var(--...)) automatically picks up the new palette — no config edit
 * required.
 */
const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '1rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        // Consume the emitted LADDER, not arithmetic off a single value.
        // tokens.css ships --radius-sm/md/lg as three independent brand values
        // (e.g. 6/10/14px); deriving md as `--radius - 2px` threw two of the
        // three steps away and silently rendered lg at 10px where the brand
        // asked for 14px. --radius is kept as the fallback so a tokens.css that
        // predates the ladder still resolves.
        lg: 'var(--radius-lg, var(--radius))',
        md: 'var(--radius-md, calc(var(--radius) - 2px))',
        sm: 'var(--radius-sm, calc(var(--radius) - 4px))',
      },
      fontFamily: {
        // The brand's typefaces, not a hardcoded Inter. tokens.css ships
        // --font-display and --font-body from the generated brand (e.g. Sora /
        // IBM Plex Sans) and this config pinned every family to Inter, so the
        // chosen typography never reached a single rendered element — the most
        // visible half of a brand, discarded one line above the colours that
        // were wired correctly. Inter stays as the fallback inside the var.
        sans: ['var(--font-body, Inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        heading: ['var(--font-display, Inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['var(--font-display, Inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['var(--font-body, Inter)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      // Motion tokens were emitted and unreachable: no utility mapped to them,
      // so every transition used Tailwind's default 150ms/ease and the brand's
      // Carbon-productive scale sat unused in tokens.css.
      transitionDuration: {
        fast: 'var(--dur-fast, 100ms)',
        base: 'var(--dur-base, 150ms)',
        slow: 'var(--dur-slow, 240ms)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out, cubic-bezier(0.165, 0.84, 0.44, 1))',
        'in-out': 'var(--ease-in-out, cubic-bezier(0.645, 0.045, 0.355, 1))',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down':
          'accordion-down var(--dur-slow, 240ms) var(--ease-out, cubic-bezier(0.165,0.84,0.44,1))',
        'accordion-up':
          'accordion-up var(--dur-slow, 240ms) var(--ease-out, cubic-bezier(0.165,0.84,0.44,1))',
      },
    },
  },
  plugins: [animate],
};

export default config;
