import {
  Home,
  Inbox,
  Users,
  User,
  Settings,
  Calendar,
  CalendarDays,
  BarChart3,
  LineChart,
  PieChart,
  Folder,
  FolderKanban,
  KanbanSquare,
  List,
  ListChecks,
  CheckSquare,
  FileText,
  Files,
  Mail,
  MessageSquare,
  Bell,
  Search,
  Star,
  Tag,
  Tags,
  Package,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Wallet,
  DollarSign,
  TrendingUp,
  Activity,
  Map,
  MapPin,
  Building2,
  Briefcase,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Grid3x3,
  Table2,
  Database,
  Bookmark,
  Heart,
  Clock,
  Zap,
  Rocket,
  Flag,
  Target,
  Compass,
  Globe,
  Image,
  Video,
  Music,
  Headphones,
  Play,
  BookOpen,
  GraduationCap,
  Stethoscope,
  Pill,
  Dumbbell,
  Leaf,
  Coffee,
  Utensils,
  Car,
  Truck,
  Plane,
  Home as HomeIcon,
  Wrench,
  Hammer,
  Paintbrush,
  Palette,
  Camera,
  Phone,
  Send,
  Share2,
  Upload,
  Download,
  Filter,
  SlidersHorizontal,
  Plus,
  Circle,
  type LucideIcon,
} from 'lucide-react';

/**
 * nav-icons — a curated lucide icon map so NAV_SECTIONS can name icons by
 * string ('inbox', 'calendar', 'kanban') without importing all of lucide into
 * the bundle. Unknown names fall back to a small dot, which reads as
 * "destination" without pretending to be a specific glyph.
 *
 * Add an icon: import it above and add a `'kebab-name': Icon` line below.
 */
const ICONS: Record<string, LucideIcon> = {
  home: Home,
  inbox: Inbox,
  users: Users,
  user: User,
  settings: Settings,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  chart: BarChart3,
  'bar-chart': BarChart3,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  folder: Folder,
  'folder-kanban': FolderKanban,
  kanban: KanbanSquare,
  board: KanbanSquare,
  list: List,
  'list-checks': ListChecks,
  'check-square': CheckSquare,
  tasks: CheckSquare,
  file: FileText,
  files: Files,
  docs: Files,
  mail: Mail,
  message: MessageSquare,
  messages: MessageSquare,
  chat: MessageSquare,
  bell: Bell,
  notifications: Bell,
  search: Search,
  star: Star,
  tag: Tag,
  tags: Tags,
  package: Package,
  inventory: Package,
  cart: ShoppingCart,
  orders: ShoppingBag,
  bag: ShoppingBag,
  card: CreditCard,
  billing: CreditCard,
  wallet: Wallet,
  dollar: DollarSign,
  money: DollarSign,
  revenue: TrendingUp,
  trending: TrendingUp,
  activity: Activity,
  map: Map,
  pin: MapPin,
  location: MapPin,
  building: Building2,
  properties: Building2,
  briefcase: Briefcase,
  deals: Briefcase,
  layers: Layers,
  dashboard: LayoutDashboard,
  grid: LayoutGrid,
  'grid-3x3': Grid3x3,
  table: Table2,
  database: Database,
  bookmark: Bookmark,
  heart: Heart,
  clock: Clock,
  time: Clock,
  zap: Zap,
  rocket: Rocket,
  flag: Flag,
  target: Target,
  goals: Target,
  compass: Compass,
  globe: Globe,
  image: Image,
  gallery: Image,
  video: Video,
  music: Music,
  headphones: Headphones,
  play: Play,
  book: BookOpen,
  courses: BookOpen,
  graduation: GraduationCap,
  stethoscope: Stethoscope,
  health: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  fitness: Dumbbell,
  leaf: Leaf,
  coffee: Coffee,
  utensils: Utensils,
  food: Utensils,
  car: Car,
  truck: Truck,
  delivery: Truck,
  plane: Plane,
  house: HomeIcon,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  palette: Palette,
  camera: Camera,
  phone: Phone,
  send: Send,
  share: Share2,
  upload: Upload,
  download: Download,
  filter: Filter,
  sliders: SlidersHorizontal,
  plus: Plus,
};

export function NavIcon({ name, className }: { name?: string; className?: string }) {
  const Icon = (name && ICONS[name]) || Circle;
  return <Icon className={className} aria-hidden="true" />;
}

export function hasIcon(name?: string): boolean {
  return !!name && name in ICONS;
}
