import {
  Home,
  Inbox,
  Users,
  Users2,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserCircle,
  Contact,
  Settings,
  Calendar,
  CalendarDays,
  CalendarCheck,
  BarChart3,
  LineChart,
  PieChart,
  Gauge,
  TrendingDown,
  Folder,
  FolderKanban,
  KanbanSquare,
  List,
  ListChecks,
  CheckSquare,
  FileText,
  FileBarChart,
  Files,
  Mail,
  MessageSquare,
  Bell,
  Search,
  Star,
  Tag,
  Tags,
  Package,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Wallet,
  Banknote,
  Receipt,
  PiggyBank,
  Landmark,
  ArrowLeftRight,
  CandlestickChart,
  Repeat,
  Hourglass,
  Timer,
  DollarSign,
  TrendingUp,
  Activity,
  Megaphone,
  Magnet,
  Workflow,
  GitBranch,
  LifeBuoy,
  Ticket,
  Plug,
  Puzzle,
  Key,
  Shield,
  ShieldCheck,
  Lock,
  Eye,
  Map,
  MapPin,
  Building2,
  Warehouse,
  Briefcase,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Grid3x3,
  Table2,
  Database,
  Bookmark,
  Heart,
  HeartPulse,
  Clock,
  Zap,
  Rocket,
  Flag,
  Target,
  Compass,
  Globe,
  Image,
  Video,
  Music,
  Headphones,
  Play,
  BookOpen,
  GraduationCap,
  Stethoscope,
  Pill,
  Dumbbell,
  Leaf,
  Coffee,
  Utensils,
  Car,
  Truck,
  Plane,
  Home as HomeIcon,
  Wrench,
  Hammer,
  Paintbrush,
  Palette,
  Camera,
  Phone,
  Send,
  Share2,
  Upload,
  Download,
  Filter,
  SlidersHorizontal,
  Plus,
  MousePointerClick,
  Store,
  CalendarClock,
  ClipboardList,
  Boxes,
  Archive,
  Trash2,
  Pencil,
  CheckCircle2,
  Sparkles,
  Printer,
  Clipboard,
  Newspaper,
  Gift,
  Percent,
  ReceiptText,
  Scissors,
  Shirt,
  HandCoins,
  Stamp,
  ScrollText,
  NotebookPen,
  type LucideIcon,
} from 'lucide-react';

import { cn } from '@/lib/utils';

/**
 * nav-icons — a curated lucide icon map so NAV_SECTIONS can name icons by
 * string ('inbox', 'subscribers', 'churn') without importing all of lucide into
 * the bundle. The map covers the common SaaS vocabulary (analytics, revenue,
 * subscribers, churn, trials, customers, invoices, pipeline, campaigns, tickets,
 * ...) so a semantic name resolves to a MEANINGFUL glyph.
 *
 * If a name is unknown, NavIcon renders a deterministic monogram (the first
 * letter) — never a generic placeholder circle, which is the "row of identical
 * dots" tell. Every nav item stays visually distinct and scannable by shape.
 *
 * Add an icon: import it above and add a `'kebab-name': Icon` line below.
 */
const ICONS: Record<string, LucideIcon> = {
  home: Home,
  overview: LayoutDashboard,
  dashboard: LayoutDashboard,
  workspace: LayoutDashboard,
  inbox: Inbox,
  users: Users,
  team: Users2,
  audience: Users2,
  user: User,
  account: UserCircle,
  customers: UserCircle,
  clients: UserCircle,
  contact: Contact,
  contacts: Contact,
  subscribers: UserCheck,
  members: UserCheck,
  subscription: Repeat,
  subscriptions: Repeat,
  churn: UserMinus,
  leads: UserPlus,
  lead: UserPlus,
  settings: Settings,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  appointments: CalendarCheck,
  bookings: CalendarCheck,
  schedule: CalendarCheck,
  chart: BarChart3,
  'bar-chart': BarChart3,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  analytics: LineChart,
  insights: LineChart,
  metrics: Gauge,
  stats: Gauge,
  performance: Gauge,
  decline: TrendingDown,
  reports: FileBarChart,
  report: FileBarChart,
  folder: Folder,
  'folder-kanban': FolderKanban,
  projects: FolderKanban,
  project: Folder,
  kanban: KanbanSquare,
  board: KanbanSquare,
  pipeline: Workflow,
  workflow: Workflow,
  stages: GitBranch,
  list: List,
  'list-checks': ListChecks,
  'check-square': CheckSquare,
  tasks: CheckSquare,
  file: FileText,
  files: Files,
  docs: Files,
  documents: Files,
  invoice: Receipt,
  invoices: Receipt,
  transactions: ArrowLeftRight,
  transaction: ArrowLeftRight,
  transfers: ArrowLeftRight,
  mail: Mail,
  email: Mail,
  campaigns: Megaphone,
  campaign: Megaphone,
  marketing: Megaphone,
  message: MessageSquare,
  messages: MessageSquare,
  chat: MessageSquare,
  support: LifeBuoy,
  tickets: Ticket,
  ticket: Ticket,
  bell: Bell,
  alerts: Bell,
  notifications: Bell,
  search: Search,
  star: Star,
  watchlist: Eye,
  tag: Tag,
  tags: Tags,
  package: Package,
  inventory: Package,
  cart: ShoppingCart,
  orders: ShoppingBag,
  bag: ShoppingBag,
  card: CreditCard,
  billing: CreditCard,
  payments: CreditCard,
  payment: CreditCard,
  wallet: Wallet,
  banknote: Banknote,
  payroll: Banknote,
  expenses: Receipt,
  budget: PiggyBank,
  savings: PiggyBank,
  accounts: Landmark,
  bank: Landmark,
  portfolio: Briefcase,
  assets: PieChart,
  trades: CandlestickChart,
  positions: CandlestickChart,
  trading: CandlestickChart,
  dollar: DollarSign,
  money: DollarSign,
  revenue: TrendingUp,
  growth: TrendingUp,
  trending: TrendingUp,
  trials: Hourglass,
  trial: Hourglass,
  pending: Timer,
  activity: Activity,
  sessions: MousePointerClick,
  events: Zap,
  integrations: Plug,
  apps: Puzzle,
  api: Key,
  keys: Key,
  security: Shield,
  compliance: ShieldCheck,
  roles: ShieldCheck,
  permissions: Lock,
  leadmagnet: Magnet,
  map: Map,
  pin: MapPin,
  location: MapPin,
  building: Building2,
  properties: Building2,
  warehouse: Warehouse,
  suppliers: Warehouse,
  briefcase: Briefcase,
  deals: Briefcase,
  layers: Layers,
  grid: LayoutGrid,
  'grid-3x3': Grid3x3,
  table: Table2,
  database: Database,
  bookmark: Bookmark,
  heart: Heart,
  patients: HeartPulse,
  clock: Clock,
  time: Clock,
  zap: Zap,
  rocket: Rocket,
  flag: Flag,
  target: Target,
  goals: Target,
  compass: Compass,
  globe: Globe,
  image: Image,
  gallery: Image,
  video: Video,
  music: Music,
  headphones: Headphones,
  play: Play,
  book: BookOpen,
  courses: BookOpen,
  classes: BookOpen,
  graduation: GraduationCap,
  students: GraduationCap,
  stethoscope: Stethoscope,
  health: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  fitness: Dumbbell,
  leaf: Leaf,
  coffee: Coffee,
  utensils: Utensils,
  food: Utensils,
  car: Car,
  truck: Truck,
  delivery: Truck,
  shipments: Truck,
  plane: Plane,
  house: HomeIcon,
  wrench: Wrench,
  hammer: Hammer,
  paintbrush: Paintbrush,
  palette: Palette,
  camera: Camera,
  phone: Phone,
  send: Send,
  share: Share2,
  upload: Upload,
  download: Download,
  filter: Filter,
  sliders: SlidersHorizontal,
  plus: Plus,

  // Literal lucide kebab names. The map above is keyed on SEMANTIC intent
  // (orders, invoices, churn); but the generator often emits the icon's own
  // lucide name (`store`, `receipt`, `calendar-clock`). Those must resolve to a
  // real glyph too, otherwise they fall through to the monogram — the exact
  // "bare S / C / R letters in the nav" defect. Every entry here is the literal
  // kebab name of an icon already imported above (or one of the additions below).
  store: Store,
  receipt: Receipt,
  'receipt-text': ReceiptText,
  'calendar-clock': CalendarClock,
  'calendar-check': CalendarCheck,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'bar-chart-3': BarChart3,
  'file-text': FileText,
  'file-bar-chart': FileBarChart,
  'message-square': MessageSquare,
  'map-pin': MapPin,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  'heart-pulse': HeartPulse,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'shield-check': ShieldCheck,
  'life-buoy': LifeBuoy,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-circle': UserCircle,
  'git-branch': GitBranch,
  'arrow-left-right': ArrowLeftRight,
  'candlestick-chart': CandlestickChart,
  'piggy-bank': PiggyBank,
  'building-2': Building2,
  'kanban-square': KanbanSquare,
  'sliders-horizontal': SlidersHorizontal,
  'mouse-pointer-click': MousePointerClick,
  'share-2': Share2,
  'clipboard-list': ClipboardList,
  'scroll-text': ScrollText,
  'notebook-pen': NotebookPen,
  'check-circle': CheckCircle2,
  'hand-coins': HandCoins,

  // Additional business vocabulary the generator reaches for across verticals
  // (retail, salon, logistics, finance, docs) — imported above, mapped here.
  storefront: Store,
  shop: Store,
  boxes: Boxes,
  stock: Boxes,
  archive: Archive,
  archived: Archive,
  trash: Trash2,
  delete: Trash2,
  edit: Pencil,
  pencil: Pencil,
  sparkles: Sparkles,
  featured: Sparkles,
  printer: Printer,
  print: Printer,
  clipboard: Clipboard,
  newspaper: Newspaper,
  news: Newspaper,
  posts: Newspaper,
  gift: Gift,
  rewards: Gift,
  percent: Percent,
  discounts: Percent,
  promotions: Percent,
  scissors: Scissors,
  services: Scissors,
  shirt: Shirt,
  products: Shirt,
  catalog: Shirt,
  commissions: HandCoins,
  stamp: Stamp,
  approvals: Stamp,
};

export function NavIcon({ name, className }: { name?: string; className?: string }) {
  const Icon = name ? ICONS[name] : undefined;
  if (Icon) return <Icon className={className} aria-hidden="true" />;
  if (name) {
    // Deterministic monogram fallback — distinct per item, reads intentional.
    // Never a generic circle (the "row of identical dots" tell).
    const letter = name.trim().charAt(0).toUpperCase();
    return (
      <span
        className={cn(
          'inline-flex items-center justify-center rounded-[5px] bg-muted text-[10px] font-semibold leading-none text-muted-foreground',
          className,
        )}
        aria-hidden="true"
      >
        {letter}
      </span>
    );
  }
  return null;
}

export function hasIcon(name?: string): boolean {
  return !!name && name in ICONS;
}
